id: A21DCEA07
title: Prayer to Pacify Military Conflict
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:25:43.493015
  last_modified_at: 2022-03-01 00:25:43.493023
